dist: trusty
sudo: required
language: go

go:
  - 1.8.x
  - tip

go_import_path: github.com/AlekSi/mysqlx

env:
  - MYSQL_IMAGE=mysql/mysql-server:5.7
  - MYSQL_IMAGE=mysql/mysql-server:8.0

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop

install:
  - go get -v -t

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make init
  - make seed
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
