dist: trusty
sudo: required
language: go

go:
  - 1.10.x
  - 1.11.x
  - master

go_import_path: github.com/AlekSi/mysqlx

env:
  global:
    - MYSQLX_TEST_DATASOURCE='mysqlx://my_user:my_password@127.0.0.1:33060/?_auth-method=PLAIN&time_zone=UTC'
  matrix:
    - MYSQL_IMAGE=mysql/mysql-server:5.7
    # - MYSQL_IMAGE=mysql/mysql-server:8.0

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop

install:
  - go get -v -t

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make init install
  - go run -v internal/wait.go
  - make seed
  - make cover
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
