// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysqlx_expect.proto

/*
Package mysqlx_expect is a generated protocol buffer package.

Expect operations

It is generated from these files:
	mysqlx_expect.proto

It has these top-level messages:
	Open
	Close
*/
package mysqlx_expect

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/AlekSi/mysqlx/internal/proto/mysqlx"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Open_CtxOperation int32

const (
	// copy the operations from the parent Expect-block
	Open_EXPECT_CTX_COPY_PREV Open_CtxOperation = 0
	// start with a empty set of operations
	Open_EXPECT_CTX_EMPTY Open_CtxOperation = 1
)

var Open_CtxOperation_name = map[int32]string{
	0: "EXPECT_CTX_COPY_PREV",
	1: "EXPECT_CTX_EMPTY",
}
var Open_CtxOperation_value = map[string]int32{
	"EXPECT_CTX_COPY_PREV": 0,
	"EXPECT_CTX_EMPTY":     1,
}

func (x Open_CtxOperation) Enum() *Open_CtxOperation {
	p := new(Open_CtxOperation)
	*p = x
	return p
}
func (x Open_CtxOperation) String() string {
	return proto.EnumName(Open_CtxOperation_name, int32(x))
}
func (x *Open_CtxOperation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Open_CtxOperation_value, data, "Open_CtxOperation")
	if err != nil {
		return err
	}
	*x = Open_CtxOperation(value)
	return nil
}
func (Open_CtxOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Open_Condition_Key int32

const (
	// Change error propagation behaviour
	Open_Condition_EXPECT_NO_ERROR Open_Condition_Key = 1
	// Check if X Protocol field exists
	Open_Condition_EXPECT_FIELD_EXIST Open_Condition_Key = 2
)

var Open_Condition_Key_name = map[int32]string{
	1: "EXPECT_NO_ERROR",
	2: "EXPECT_FIELD_EXIST",
}
var Open_Condition_Key_value = map[string]int32{
	"EXPECT_NO_ERROR":    1,
	"EXPECT_FIELD_EXIST": 2,
}

func (x Open_Condition_Key) Enum() *Open_Condition_Key {
	p := new(Open_Condition_Key)
	*p = x
	return p
}
func (x Open_Condition_Key) String() string {
	return proto.EnumName(Open_Condition_Key_name, int32(x))
}
func (x *Open_Condition_Key) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Open_Condition_Key_value, data, "Open_Condition_Key")
	if err != nil {
		return err
	}
	*x = Open_Condition_Key(value)
	return nil
}
func (Open_Condition_Key) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 0} }

type Open_Condition_ConditionOperation int32

const (
	// set the condition
	//
	// set, if not set
	// overwrite, if set
	Open_Condition_EXPECT_OP_SET Open_Condition_ConditionOperation = 0
	// unset the condition
	Open_Condition_EXPECT_OP_UNSET Open_Condition_ConditionOperation = 1
)

var Open_Condition_ConditionOperation_name = map[int32]string{
	0: "EXPECT_OP_SET",
	1: "EXPECT_OP_UNSET",
}
var Open_Condition_ConditionOperation_value = map[string]int32{
	"EXPECT_OP_SET":   0,
	"EXPECT_OP_UNSET": 1,
}

func (x Open_Condition_ConditionOperation) Enum() *Open_Condition_ConditionOperation {
	p := new(Open_Condition_ConditionOperation)
	*p = x
	return p
}
func (x Open_Condition_ConditionOperation) String() string {
	return proto.EnumName(Open_Condition_ConditionOperation_name, int32(x))
}
func (x *Open_Condition_ConditionOperation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Open_Condition_ConditionOperation_value, data, "Open_Condition_ConditionOperation")
	if err != nil {
		return err
	}
	*x = Open_Condition_ConditionOperation(value)
	return nil
}
func (Open_Condition_ConditionOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 1}
}

// open an Expect block and set/unset the conditions that have to be fulfilled
//
// if any of the conditions fail, all enclosed messages will fail with
// a Mysqlx.Error message.
//
// :returns: :protobuf:msg:`Mysqlx::Ok` on success, :protobuf:msg:`Mysqlx::Error` on error
//
type Open struct {
	Op               *Open_CtxOperation `protobuf:"varint,1,opt,name=op,enum=Mysqlx.Expect.Open_CtxOperation,def=0" json:"op,omitempty"`
	Cond             []*Open_Condition  `protobuf:"bytes,2,rep,name=cond" json:"cond,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Open) Reset()                    { *m = Open{} }
func (m *Open) String() string            { return proto.CompactTextString(m) }
func (*Open) ProtoMessage()               {}
func (*Open) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Open_Op Open_CtxOperation = Open_EXPECT_CTX_COPY_PREV

func (m *Open) GetOp() Open_CtxOperation {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return Default_Open_Op
}

func (m *Open) GetCond() []*Open_Condition {
	if m != nil {
		return m.Cond
	}
	return nil
}

type Open_Condition struct {
	ConditionKey     *uint32                            `protobuf:"varint,1,req,name=condition_key,json=conditionKey" json:"condition_key,omitempty"`
	ConditionValue   []byte                             `protobuf:"bytes,2,opt,name=condition_value,json=conditionValue" json:"condition_value,omitempty"`
	Op               *Open_Condition_ConditionOperation `protobuf:"varint,3,opt,name=op,enum=Mysqlx.Expect.Open_Condition_ConditionOperation,def=0" json:"op,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *Open_Condition) Reset()                    { *m = Open_Condition{} }
func (m *Open_Condition) String() string            { return proto.CompactTextString(m) }
func (*Open_Condition) ProtoMessage()               {}
func (*Open_Condition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

const Default_Open_Condition_Op Open_Condition_ConditionOperation = Open_Condition_EXPECT_OP_SET

func (m *Open_Condition) GetConditionKey() uint32 {
	if m != nil && m.ConditionKey != nil {
		return *m.ConditionKey
	}
	return 0
}

func (m *Open_Condition) GetConditionValue() []byte {
	if m != nil {
		return m.ConditionValue
	}
	return nil
}

func (m *Open_Condition) GetOp() Open_Condition_ConditionOperation {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return Default_Open_Condition_Op
}

// close a Expect block
//
// closing a Expect block restores the state of the previous Expect block
// for the following messages
//
// :returns: :protobuf:msg:`Mysqlx::Ok` on success, :protobuf:msg:`Mysqlx::Error` on error
type Close struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Close) Reset()                    { *m = Close{} }
func (m *Close) String() string            { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()               {}
func (*Close) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Open)(nil), "Mysqlx.Expect.Open")
	proto.RegisterType((*Open_Condition)(nil), "Mysqlx.Expect.Open.Condition")
	proto.RegisterType((*Close)(nil), "Mysqlx.Expect.Close")
	proto.RegisterEnum("Mysqlx.Expect.Open_CtxOperation", Open_CtxOperation_name, Open_CtxOperation_value)
	proto.RegisterEnum("Mysqlx.Expect.Open_Condition_Key", Open_Condition_Key_name, Open_Condition_Key_value)
	proto.RegisterEnum("Mysqlx.Expect.Open_Condition_ConditionOperation", Open_Condition_ConditionOperation_name, Open_Condition_ConditionOperation_value)
}

func init() { proto.RegisterFile("mysqlx_expect.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0xb1, 0x4d, 0x0f, 0x9d, 0xda, 0xe0, 0x2e, 0xa8, 0x35, 0x48, 0x95, 0x2c, 0xf7, 0x50,
	0x9f, 0x56, 0x94, 0x23, 0x8a, 0x72, 0x88, 0xb3, 0x48, 0x28, 0x81, 0xb5, 0x16, 0x07, 0xc1, 0x69,
	0x45, 0xcc, 0x46, 0x22, 0x01, 0xaf, 0x03, 0x26, 0x82, 0x37, 0xc8, 0x43, 0xe4, 0xf9, 0x72, 0xc8,
	0x53, 0x44, 0x36, 0x0e, 0x7f, 0x14, 0x94, 0xdb, 0xce, 0x6f, 0xbe, 0xfd, 0x34, 0xdf, 0x68, 0xa0,
	0x32, 0xdf, 0x2c, 0x1f, 0x67, 0x6b, 0x2e, 0xd6, 0xb1, 0x08, 0x13, 0x1c, 0x2f, 0x64, 0x22, 0x91,
	0xd1, 0xcd, 0x20, 0x26, 0x19, 0xac, 0xeb, 0x5b, 0xcd, 0xb6, 0xe9, 0xbc, 0x6a, 0x50, 0xa4, 0xb1,
	0x88, 0x50, 0x1b, 0x54, 0x19, 0x5b, 0x8a, 0xad, 0xb8, 0xa5, 0xa6, 0x8d, 0x8f, 0xbe, 0xe0, 0x54,
	0x80, 0xbd, 0x64, 0x4d, 0x63, 0xb1, 0x18, 0x27, 0x53, 0x19, 0xb5, 0xaa, 0x64, 0xe8, 0x13, 0x2f,
	0xe0, 0x5e, 0x30, 0xe4, 0x1e, 0xf5, 0x47, 0xdc, 0x67, 0x64, 0xc0, 0x54, 0x19, 0xa3, 0xff, 0x50,
	0x0c, 0x65, 0x34, 0xb1, 0x54, 0x5b, 0x73, 0x7f, 0x34, 0xff, 0x9c, 0x74, 0x92, 0xd1, 0x64, 0x9a,
	0xda, 0xb0, 0x4c, 0x5a, 0x7f, 0x51, 0xe1, 0xfb, 0x8e, 0xa1, 0xbf, 0x60, 0x84, 0x1f, 0x05, 0x7f,
	0x10, 0x1b, 0x4b, 0xb1, 0x55, 0xd7, 0x60, 0xfa, 0x0e, 0x5e, 0x89, 0x0d, 0xfa, 0x07, 0xe5, 0xbd,
	0xe8, 0x69, 0x3c, 0x5b, 0x09, 0x4b, 0xb5, 0x15, 0x57, 0x67, 0xa5, 0x1d, 0x1e, 0xa4, 0x14, 0xd1,
	0x2c, 0x96, 0x96, 0xc5, 0x6a, 0x7c, 0x39, 0xcc, 0xfe, 0xb5, 0x8f, 0x69, 0xe4, 0x31, 0xa9, 0xcf,
	0xfb, 0x24, 0x48, 0xf3, 0x39, 0x4d, 0xd0, 0xd2, 0x01, 0x2a, 0x50, 0xce, 0x7b, 0x3d, 0xca, 0x09,
	0x63, 0x94, 0x99, 0x0a, 0xfa, 0x05, 0x28, 0x87, 0xed, 0x0e, 0xb9, 0xbe, 0xe4, 0x64, 0xd8, 0xe9,
	0x07, 0xa6, 0xea, 0x9c, 0x01, 0xfa, 0x6c, 0x8e, 0x7e, 0xc2, 0xb1, 0xbd, 0x59, 0x38, 0x70, 0xa5,
	0x3e, 0xbf, 0xe9, 0xa5, 0x50, 0x71, 0xce, 0x41, 0x3f, 0xdc, 0x3d, 0xb2, 0xe0, 0xe4, 0xf6, 0xcd,
	0x02, 0xaa, 0x82, 0x79, 0xd0, 0x21, 0x5d, 0x3f, 0x18, 0x99, 0x4a, 0xab, 0xf8, 0xfc, 0xd6, 0xb0,
	0x1c, 0x03, 0xbe, 0x79, 0x33, 0xb9, 0x14, 0x59, 0x59, 0xbb, 0xa8, 0xc1, 0xef, 0x50, 0xce, 0x71,
	0x76, 0x0b, 0x38, 0xbc, 0xc7, 0xf9, 0x3d, 0xdc, 0xae, 0xee, 0xde, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x4e, 0x74, 0xd8, 0x0a, 0x45, 0x02, 0x00, 0x00,
}
